### ISSUE TITLE
Unable to run the attestation client application

### ISSUE THREAD

**Issue by ShannonSD** [Azure/confidential-computing-cvm-guest-attestation#2]
I was unable to run the attestation as it fails immediately after successfully retrieving the VCEK certificate. The Send Request is failing with the following error:

![Azure_AMD-Attestation-Error](https://user-images.githubusercontent.com/10088118/180209822-c5bea0c9-882e-4894-822d-a0e58d98f3e7.JPG)

Could you provide some insight into what's causing this error?

**Comment by akashgupta29** [comment]
@ShannonSD your screenshot shows that attestation failed on your CVM because secure boot is disabled. Can you turn it ON and rerun your client?
