### ISSUE TITLE
Secure Key Release App enhancements

### ISSUE THREAD

**Issue by sid-habu** [Azure/confidential-computing-cvm-guest-attestation#25]
In the `cvm-securekey-release-app` app

1. The MAA URL used for SKR flow is hardcoded to `https://sharedweu.weu.attest.azure.net/` and doesn't use the custom URL passed by the client
2. There is no support to pass in custom `nonce` in the `client_payload` MAA token by the client
3.  If multiple managed identities are assigned to the Confidential VM (AKS with Azure Policy), IMDS auth fails as it cannot determine the `client_id`

**Comment by sid-habu** [comment]
Have sent a PR to support/fix the above

**Comment by canfikret** [comment]
Thank you for your contribution, Siddharth. PR is approved.
